# base system configuration
---
- name: install base system configuration
  hosts: localhost

  tasks:
    - name: add vim repository
      become: true
      apt_repository:
        repo: ppa:jonathonf/vim
        update_cache: false

    - name: add alacritty repository
      become: true
      apt_repository:
        repo: ppa:mmstick76/alacritty
        update_cache: false

    - name: add docker repository
      become: true
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        update_cache: false

    - name: add docker pgp apt Key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: atp-get upgrade
      become: true
      apt:
        upgrade: full
        update_cache: true

    - name: apt install system tools
      become: true
      apt:
        cache_valid_time: 1200
        state: latest
        package:
          - git
          - vim
          - jq
          - htop
          - curl
          - xclip
          - tree
          - direnv
          - byobu
          - tmux
          - alacritty
          - net-tools
          - ffmpeg  # used by youtube-dl

          # docker
          - docker-ce
          - docker-ce-cli
          - containerd.io

          # python related
          - g++
          - libffi-dev
          - libssl-dev
          - python3-dev
          - python3-pip
          - python3-venv

    - name: add fmoor to docker group
      become: true
      user:
        name: fmoor
        append: yes
        groups: docker

    - name: install tools from pypi
      pip:
        extra_args: --user
        name:
          - docker-compose
          - dtrx

- import_playbook: go.yml
- import_playbook: javascript.yml
- import_playbook: dotfiles.yml
- import_playbook: gnome.yml

- hosts: localhost
  tasks:
    - name: checkout notes
      git:
        repo: git@bitbucket.org:fmoor/notes.git
        dest: ~/src/notes
        version: master
        key_file: ~/.ssh/id_rsa

    - name: checkout devenv
      git:
        repo: git@github.com:fmoor/devenv.git
        dest: ~/src/devenv
        version: master
        key_file: ~/.ssh/id_rsa

    - debug:
        msg: Its probably a good idea to reboot now.
