---
- name: install dot files
  hosts: localhost

  tasks:
    - name: install dependencies from pypi
      pip:
        extra_args: --user
        name:
          # aliased in bashrc
          - youtube-dl

          - python-language-server[all]
          - pyls-mypy

          # used by vim plugin dense-analysis/ale
          - yamllint
          - flake8
          - mypy

    - name: install svelte language server
      community.general.npm:
        name: svelte-language-server
        global: yes

    - name: install git prompt script
      get_url:
        url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
        dest: ~/.git-prompt.sh

    - name: checkout dotfiles
      git:
        repo: git@github.com:fmoor/dotfiles.git
        dest: ~/src/dotfiles
        version: master
        key_file: ~/.ssh/id_rsa

    - name: link .bashrc
      file:
        state: link
        src: ~/src/dotfiles/bashrc
        path: ~/.bashrc
        force: yes

    # https://github.com/alacritty/alacritty#configuration
    - name: link alacritty.yml
      file:
        state: link
        src: ~/src/dotfiles/alacritty.yml
        path: ~/.alacritty.yml

    - name: create byobu config directory
      file:
        state: directory
        path: ~/.byobu

    - name: link .tmux.conf
      file:
        state: link
        src: ~/src/dotfiles/tmux
        path: ~/.byobu/.tmux.conf
        force: yes

    - name: link neovim config
      file:
        state: link
        src: ~/src/dotfiles/nvim
        path: ~/.config/nvim
        force: yes

    - name: link .vimrc
      file:
        state: link
        src: ~/src/dotfiles/vimrc
        path: ~/.vimrc
        force: yes

    - name: install neovim pulgins
      command: nvim +'PlugInstall --sycn' +qa

    - name: link .gitconfig
      file:
        state: link
        src: ~/src/dotfiles/gitconfig
        path: ~/.gitconfig

    - name: link .gitignore_global
      file:
        state: link
        src: ~/src/dotfiles/gitignore_global
        path: ~/.gitignore_global

    - name: link user mypy.ini
      file:
        state: link
        src: ~/src/dotfiles/mypy.ini
        path: ~/.mypy.ini

    - name: link firefox config
      file:
        state: link
        src: ~/src/dotfiles/firefox.js
        path: "~/.mozilla/firefox/{{ item }}/user.js"
      with_ini:
        - 'Path section=Profile0 file=~/.mozilla/firefox/profiles.ini'
