# $ ansible-playbook -K pycharm.yml

---
- hosts: localhost

  vars:
    pycharm_version: "2018.3.4"

  tasks:
    - name: install pycharm
      unarchive:
        src: https://download.jetbrains.com/python/pycharm-community-{{ pycharm_version }}.tar.gz
        remote_src: yes
        dest: /opt/
      become: yes

    - name: register pycharm with gnome
      template:
        src: pycharm.desktop
        dest: /usr/share/applications/jetbrains-pycharm-ce.desktop
      become: yes
