---
# http://www.maartenbaert.be/simplescreenrecorder/
- hosts: localhost

  tasks:
  - name: install simplescreenrecorder
    become: yes
    apt:
      cache_valid_time: 3600
      pkg:
        - simplescreenrecorder
        - simplescreenrecorder-lib
