---
- name: install wireshark
  hosts: localhost

  tasks:
    - name: add wireshark repository
      become: yes
      apt_repository:
        repo: ppa:wireshark-dev/stable
        update_cache: false

    - name: install wireshark
      become: yes
      apt:
        update_cache: yes
        state: latest
        package: wireshark

    - name: allow non root capture
      become: yes
      debconf:
        name: wireshark-common
        question: wireshark-common/install-setuid
        value: 'true'
        vtype: select

    - name: add fmoor to wireshark group
      become: yes
      user:
        name: fmoor
        append: yes
        groups: wireshark
